### ISSUE TITLE
Некорректное поведение: отображение перевода нуля

### ISSUE THREAD

**Issue by x73495** [Dima29koz/calculator#1]
# Описание
Результат перевода нуля не отображается

# Воспроизведение
1) Вкладка "Системы счисления"
2) Ввод "0" в поле "Число"
3) Ввод "10" в после "с. осн"
4) Ввод "11" в после "н. осн"
5) Нажатие нижней клавиши "Вычислить"

# Результат

## Ожидаемый
Отображено "= 0 в 11"

## Фактический
Отображено "= в 11"

**Comment by Dima29koz** [comment]
будет исправлено в версии v1.1
