### ISSUE TITLE
Неправильно считает

### ISSUE THREAD

**Issue by boris1418** [Dima29koz/calculator#11]
При вводе значений в шестнадцатиричной системе счисления с использованием операции умножения выводится не правильное значение
![image](https://user-images.githubusercontent.com/70647787/134229829-1a23bbc9-c885-4bf9-940e-893cbbddfcd8.png)

**Comment by Dima29koz** [comment]
Приложение работает корректно. Чтобы убедиться в этом можете воспользоваться сервисом https://numsys.ru/
