### ISSUE TITLE
Некорректное поведение: % от 0.0003

### ISSUE THREAD

**Issue by x73495** [Dima29koz/calculator#2]
# Описание
Операция деления на 100 дает некорректный результат при использовании с числом 0.0003

# Воспроизведение
1) Вкладка "Обычный калькулятор"
2) Ввод "0.0003"
3) Нажатие "%"

# Результат

## Ожидаемый
Отображено "= 3e-06"

## Фактический
Отображено "= 2.999...9997e-06"

**Comment by Dima29koz** [comment]
будет исправлено в версии v1.1
