### ISSUE TITLE
Некорректное поведение: 0.0003 / 10

### ISSUE THREAD

**Issue by x73495** [Dima29koz/calculator#3]
# Описание
Деление числа 0.0003 на 10 дает некорректный результат

# Воспроизведение
1) Вкладка "Обычный калькулятор"
2) Ввод "0.0003"
3) Нажатие "/"
4) Ввод "10"

# Результат

## Ожидаемый
Отображено "= 3e-05"

## Фактический
Отображено "= 2.999...9997e-05"

**Comment by Dima29koz** [comment]
будет исправлено в версии v1.1
