### ISSUE TITLE
Некорректное поведение: изменение числа в экспоненциальной записи

### ISSUE THREAD

**Issue by x73495** [Dima29koz/calculator#4]
# Описание
При попытке добавления десятичной части числу 1e-05 и умножения такового на 2, программа отображает некорректный результат

# Воспроизведение
1) Вкладка "Обычный калькулятор"
2) Ввод "0.001"
3) Нажатие "%"
4) Ввод ".1*2"

# Результат

## Ожидаемый
Отображено "= 2.2e-05"

## Фактический
Отображено "= 1e-05"

**Comment by Dima29koz** [comment]
будет исправлено в версии v1.1
