### ISSUE TITLE
Некорректное поведение: операции с числом при основании 0

### ISSUE THREAD

**Issue by x73495** [Dima29koz/calculator#5]
# Описание
Программа не выдает ошибку при операции с числом 1 при основании 0

# Воспроизведение
1) Вкладка "Системы счисления"
2) Ввод "1" в поля "Число 1" и "Число 2"
3) Ввод "0" в каждое поле "осн" (одно из полей может также содержать любое валидное значение)
4) Выбор операции "+"
5) Нажатие "Вычислить"

# Результат

## Ожидаемый
Отображено "Ошибка ввода!"

## Фактический
Отображено "= 2 в 10"

**Comment by Dima29koz** [comment]
будет исправлено в версии v1.1
