### ISSUE TITLE
Некорректное поведение: 0/1 != 0/-1

### ISSUE THREAD

**Issue by x73495** [Dima29koz/calculator#6]
# Описание
Программа выделяет результаты деления 0 на 1 и 0 на -1, как различные

# Воспроизведение
1) Вкладка "Системы счисления"
2) Ввод "0" в поле "Число 1"
3) Ввод "10" в оба поля "осн"
4) Ввод "1" в поле "Число 2"
5) Выбор операции "/"
6) Нажатие "Вычислить" (отображено "= 0.0 в 10")
7) Ввод "-1" в поле "Число 2"
8) Нажатие "Вычислить"

# Результат

## Ожидаемый
Отображено "= 0.0 в 10"

## Фактический
Отображено "= -0.0 в 10"

**Comment by Dima29koz** [comment]
будет исправлено в версии v1.1
